<?php
/**
 * ExistingSaleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHP Point Of Sale API
 *
 * PHP Point Of Sale API  You can find out more about PHP POS at [https://phppointofsale.com](https://phppointofsale.com)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@phppointofsale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ExistingSaleTest Class Doc Comment
 *
 * @category    Class
 * @description ExistingSale
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExistingSaleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExistingSale"
     */
    public function testExistingSale()
    {
    }

    /**
     * Test attribute "sale_id"
     */
    public function testPropertySaleId()
    {
    }

    /**
     * Test attribute "store_account_payment"
     */
    public function testPropertyStoreAccountPayment()
    {
    }

    /**
     * Test attribute "sale_time"
     */
    public function testPropertySaleTime()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "profit"
     */
    public function testPropertyProfit()
    {
    }

    /**
     * Test attribute "tip"
     */
    public function testPropertyTip()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "customer_first_name"
     */
    public function testPropertyCustomerFirstName()
    {
    }

    /**
     * Test attribute "customer_last_name"
     */
    public function testPropertyCustomerLastName()
    {
    }

    /**
     * Test attribute "customer_email"
     */
    public function testPropertyCustomerEmail()
    {
    }

    /**
     * Test attribute "customer_phone_number"
     */
    public function testPropertyCustomerPhoneNumber()
    {
    }

    /**
     * Test attribute "customer_address_1"
     */
    public function testPropertyCustomerAddress1()
    {
    }

    /**
     * Test attribute "customer_address_2"
     */
    public function testPropertyCustomerAddress2()
    {
    }

    /**
     * Test attribute "customer_city"
     */
    public function testPropertyCustomerCity()
    {
    }

    /**
     * Test attribute "customer_state"
     */
    public function testPropertyCustomerState()
    {
    }

    /**
     * Test attribute "customer_zip"
     */
    public function testPropertyCustomerZip()
    {
    }

    /**
     * Test attribute "customer_country"
     */
    public function testPropertyCustomerCountry()
    {
    }

    /**
     * Test attribute "customer_comments"
     */
    public function testPropertyCustomerComments()
    {
    }

    /**
     * Test attribute "customer_internal_notes"
     */
    public function testPropertyCustomerInternalNotes()
    {
    }

    /**
     * Test attribute "customer_company_name"
     */
    public function testPropertyCustomerCompanyName()
    {
    }

    /**
     * Test attribute "customer_tier_id"
     */
    public function testPropertyCustomerTierId()
    {
    }

    /**
     * Test attribute "customer_account_number"
     */
    public function testPropertyCustomerAccountNumber()
    {
    }

    /**
     * Test attribute "customer_taxable"
     */
    public function testPropertyCustomerTaxable()
    {
    }

    /**
     * Test attribute "customer_tax_certificate"
     */
    public function testPropertyCustomerTaxCertificate()
    {
    }

    /**
     * Test attribute "customer_override_default_tax"
     */
    public function testPropertyCustomerOverrideDefaultTax()
    {
    }

    /**
     * Test attribute "customer_tax_class_id"
     */
    public function testPropertyCustomerTaxClassId()
    {
    }

    /**
     * Test attribute "customer_balance"
     */
    public function testPropertyCustomerBalance()
    {
    }

    /**
     * Test attribute "customer_credit_limit"
     */
    public function testPropertyCustomerCreditLimit()
    {
    }

    /**
     * Test attribute "customer_disable_loyalty"
     */
    public function testPropertyCustomerDisableLoyalty()
    {
    }

    /**
     * Test attribute "customer_points"
     */
    public function testPropertyCustomerPoints()
    {
    }

    /**
     * Test attribute "customer_image_url"
     */
    public function testPropertyCustomerImageUrl()
    {
    }

    /**
     * Test attribute "customer_created_at"
     */
    public function testPropertyCustomerCreatedAt()
    {
    }

    /**
     * Test attribute "customer_location_id"
     */
    public function testPropertyCustomerLocationId()
    {
    }
}
