<?php
/**
 * ReceivingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHP Point Of Sale API
 *
 * PHP Point Of Sale API  You can find out more about PHP POS at [https://phppointofsale.com](https://phppointofsale.com)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@phppointofsale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ReceivingTest Class Doc Comment
 *
 * @category    Class
 * @description Receiving
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReceivingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Receiving"
     */
    public function testReceiving()
    {
    }

    /**
     * Test attribute "receiving_id"
     */
    public function testPropertyReceivingId()
    {
    }

    /**
     * Test attribute "receiving_time"
     */
    public function testPropertyReceivingTime()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "supplier_first_name"
     */
    public function testPropertySupplierFirstName()
    {
    }

    /**
     * Test attribute "supplier_last_name"
     */
    public function testPropertySupplierLastName()
    {
    }

    /**
     * Test attribute "supplier_email"
     */
    public function testPropertySupplierEmail()
    {
    }

    /**
     * Test attribute "supplier_phone_number"
     */
    public function testPropertySupplierPhoneNumber()
    {
    }

    /**
     * Test attribute "supplier_address_1"
     */
    public function testPropertySupplierAddress1()
    {
    }

    /**
     * Test attribute "supplier_address_2"
     */
    public function testPropertySupplierAddress2()
    {
    }

    /**
     * Test attribute "supplier_city"
     */
    public function testPropertySupplierCity()
    {
    }

    /**
     * Test attribute "supplier_state"
     */
    public function testPropertySupplierState()
    {
    }

    /**
     * Test attribute "supplier_zip"
     */
    public function testPropertySupplierZip()
    {
    }

    /**
     * Test attribute "supplier_country"
     */
    public function testPropertySupplierCountry()
    {
    }

    /**
     * Test attribute "supplier_comments"
     */
    public function testPropertySupplierComments()
    {
    }

    /**
     * Test attribute "supplier_company_name"
     */
    public function testPropertySupplierCompanyName()
    {
    }

    /**
     * Test attribute "supplier_account_number"
     */
    public function testPropertySupplierAccountNumber()
    {
    }

    /**
     * Test attribute "supplier_balance"
     */
    public function testPropertySupplierBalance()
    {
    }

    /**
     * Test attribute "supplier_override_default_tax"
     */
    public function testPropertySupplierOverrideDefaultTax()
    {
    }

    /**
     * Test attribute "supplier_tax_class_id"
     */
    public function testPropertySupplierTaxClassId()
    {
    }

    /**
     * Test attribute "supplier_image_url"
     */
    public function testPropertySupplierImageUrl()
    {
    }

    /**
     * Test attribute "supplier_created_at"
     */
    public function testPropertySupplierCreatedAt()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "supplier_id"
     */
    public function testPropertySupplierId()
    {
    }

    /**
     * Test attribute "transfer_location_id"
     */
    public function testPropertyTransferLocationId()
    {
    }

    /**
     * Test attribute "is_po"
     */
    public function testPropertyIsPo()
    {
    }

    /**
     * Test attribute "cart_items"
     */
    public function testPropertyCartItems()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "employee_id"
     */
    public function testPropertyEmployeeId()
    {
    }

    /**
     * Test attribute "register_id"
     */
    public function testPropertyRegisterId()
    {
    }

    /**
     * Test attribute "excluded_taxes"
     */
    public function testPropertyExcludedTaxes()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "paid_store_account_ids"
     */
    public function testPropertyPaidStoreAccountIds()
    {
    }

    /**
     * Test attribute "change_cart_date"
     */
    public function testPropertyChangeCartDate()
    {
    }

    /**
     * Test attribute "suspended"
     */
    public function testPropertySuspended()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "payments"
     */
    public function testPropertyPayments()
    {
    }
}
