CREATE TABLE IF NOT EXISTS tickets (
    record_number INT AUTO_INCREMENT,
    firstname VARCHAR(30) NOT NULL,
	lastname VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL,
	vin INT(17),
    start_date DATE,
    due_date DATE,
    check_in_date DATE,
    status TINYINT NOT NULL,
    priority TINYINT NOT NULL,
    description TEXT,
    image1 BLOB,
    image2 BLOB,
    image3 BLOB,
    image4 BLOB,
    image5 BLOB,
    make VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    year INT(4),
    phone INT(10),
    buget INT(6),
    keys VARCHAR(5) NOT NULL,
    existing_dmg1_disc TEXT,
    existing_dmg1_image BLOB,
    existing_dmg2_disc TEXT,
    existing_dmg2_image BLOB,
    existing_dmg3_disc TEXT,
    existing_dmg3_image BLOB,
    existing_dmg4_disc TEXT,
    existing_dmg5_image BLOB,
    PRIMARY KEY (record_number)
) 