<?php
/**
 * EmployeesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHP Point Of Sale API
 *
 * PHP Point Of Sale API  You can find out more about PHP POS at [https://phppointofsale.com](https://phppointofsale.com)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@phppointofsale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmployeesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmployeesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addEmployee
     *
     * Add a new employee to the store.
     *
     */
    public function testAddEmployee()
    {
    }

    /**
     * Test case for batchEmployee
     *
     * Bulk create, update, and delete employees.
     *
     */
    public function testBatchEmployee()
    {
    }

    /**
     * Test case for deleteEmployee
     *
     * Deletes a employee.
     *
     */
    public function testDeleteEmployee()
    {
    }

    /**
     * Test case for getEmployeeByPersonId
     *
     * Find person by Person ID.
     *
     */
    public function testGetEmployeeByPersonId()
    {
    }

    /**
     * Test case for searchEmployees
     *
     * Search/list employees.
     *
     */
    public function testSearchEmployees()
    {
    }

    /**
     * Test case for updateEmployee
     *
     * Update an existing employee.
     *
     */
    public function testUpdateEmployee()
    {
    }
}
