<?php
/**
 * PriceRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHP Point Of Sale API
 *
 * PHP Point Of Sale API  You can find out more about PHP POS at [https://phppointofsale.com](https://phppointofsale.com)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@phppointofsale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PriceRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PriceRulesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addPriceRule
     *
     * Add a new price rule to the POS.
     *
     */
    public function testAddPriceRule()
    {
    }

    /**
     * Test case for batchPriceRule
     *
     * Bulk create, update, and delete price rules.
     *
     */
    public function testBatchPriceRule()
    {
    }

    /**
     * Test case for deletePriceRule
     *
     * Deletes a price _rule.
     *
     */
    public function testDeletePriceRule()
    {
    }

    /**
     * Test case for getPriceRuleByID
     *
     * Find price rule by price rule ID.
     *
     */
    public function testGetPriceRuleByID()
    {
    }

    /**
     * Test case for searchPriceRules
     *
     * Search/list price rules.
     *
     */
    public function testSearchPriceRules()
    {
    }

    /**
     * Test case for updatePriceRule
     *
     * Update a price rule.
     *
     */
    public function testUpdatePriceRule()
    {
    }
}
